version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: takumi
      POSTGRES_PASSWORD: takumi
      POSTGRES_DB: todo
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres-script:/docker-entrypoint-initdb.d