/*
 * todos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetTask200Response struct {
	Tasks []Task `json:"tasks,omitempty"`
}

// AssertGetTask200ResponseRequired checks if the required fields are not zero-ed
func AssertGetTask200ResponseRequired(obj GetTask200Response) error {
	return nil
}

// AssertRecurseGetTask200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetTask200Response (e.g. [][]GetTask200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetTask200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetTask200Response, ok := obj.(GetTask200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetTask200ResponseRequired(aGetTask200Response)
	})
}
